# Generated by Django 5.2.17 on 2026-10-01 06:42

import apps.utils.asset_paths
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_settings', '0001_initial'),
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('actionbar', models.CharField(blank=True, default='', max_length=255)),
                ('cover_image', models.ImageField(max_length=500, upload_to=apps.utils.asset_paths.category_cover_upload_path)),
                ('api_option', models.CharField(blank=True, default='', max_length=100)),
                ('sort_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='app_settings.appsetting')),
                ('orientation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='lookup.orientation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='category.category')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='lookup.tag')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='lookup.recordstatus')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='lookup.tag')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='lookup.assetvariant')),
            ],
            options={
                'db_table': 'category_homecategory',
                'ordering': ('sort_order', 'title'),
                'indexes': [models.Index(fields=['app', 'section', 'status', 'sort_order'], name='homecat_app_section_status_idx'), models.Index(fields=['app', 'parent'], name='homecat_app_parent_idx'), models.Index(fields=['app', 'variant', 'status'], name='homecat_app_variant_status_idx')],
            },
        ),
    ]
