# Generated by Django 5.2.17 on 2026-10-01 06:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_settings_appsetting',
                'ordering': ('sort_order', 'label'),
            },
        ),
    ]
