# Generated by Django 5.2.17 on 2026-10-01 06:42

import apps.utils.asset_paths
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('effect', models.CharField(max_length=100)),
                ('cover', models.ImageField(max_length=500, upload_to=apps.utils.asset_paths.effect_cover_upload_path)),
                ('file', models.FileField(max_length=500, upload_to=apps.utils.asset_paths.effect_file_upload_path)),
                ('sort_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='category.category')),
                ('effect_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='effects', to='lookup.effecttype')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='effects', to='lookup.recordstatus')),
                ('tags', models.ManyToManyField(blank=True, db_table='effects_effect_tags', related_name='effects', to='lookup.tag')),
            ],
            options={
                'db_table': 'effects_effect',
                'ordering': ('sort_order', 'title'),
                'indexes': [models.Index(fields=['category', 'status', 'sort_order'], name='effect_cat_status_sort_idx'), models.Index(fields=['effect_type', 'status'], name='effect_type_status_idx')],
            },
        ),
    ]
