# Generated by Django 5.2.17 on 2026-10-06 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effects', '0001_initial'),
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE effects_effect_tags "
                        "DROP CONSTRAINT effects_effect_tags_pkey, "
                        "DROP CONSTRAINT effects_effect_tags_effect_id_tag_id_223b0f09_uniq, "
                        "DROP COLUMN id, "
                        "ADD CONSTRAINT effects_effect_tags_pkey PRIMARY KEY (effect_id, tag_id)"
                    ),
                    reverse_sql=(
                        "ALTER TABLE effects_effect_tags ADD COLUMN id bigserial; "
                        "ALTER TABLE effects_effect_tags DROP CONSTRAINT effects_effect_tags_pkey; "
                        "ALTER TABLE effects_effect_tags ADD CONSTRAINT effects_effect_tags_pkey PRIMARY KEY (id); "
                        "ALTER TABLE effects_effect_tags ADD CONSTRAINT effects_effect_tags_effect_id_tag_id_223b0f09_uniq UNIQUE (effect_id, tag_id)"
                    ),
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='EffectTag',
                    fields=[
                        ('pk', models.CompositePrimaryKey('effect_id', 'tag_id', blank=True, editable=False, primary_key=True, serialize=False)),
                        ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='effects.effect')),
                        ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lookup.tag')),
                    ],
                    options={'db_table': 'effects_effect_tags'},
                ),
                migrations.AlterField(
                    model_name='effect',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='effects', through='effects.EffectTag', through_fields=('effect', 'tag'), to='lookup.tag'),
                ),
            ],
        ),
    ]
