# Generated by Django 5.2.17 on 2026-09-25 05:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_category_status_alter_frame_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='title',
            new_name='lable',
        ),
        migrations.RemoveField(
            model_name='app',
            name='phone',
        ),
        migrations.AddField(
            model_name='app',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 25, 5, 4, 9, 996970, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='app',
            name='sortorder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apps', to='assets.recordstatus'),
        ),
        migrations.AddField(
            model_name='app',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='cover',
            field=models.ImageField(max_length=500, upload_to=''),
        ),
    ]
