# Generated by Django 5.2.17 on 2026-09-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_rename_title_app_lable_remove_app_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='slug',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='app',
            name='sortorder',
            field=models.IntegerField(),
        ),
    ]
