# Generated by Django 5.2.17 on 2026-10-01 06:42

import apps.utils.asset_paths
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('editor', models.CharField(default='frames', max_length=255)),
                ('ratio_width', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ratio_height', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image_picker', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='category.category')),
                ('frame_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frames', to='lookup.frametype')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frames', to='lookup.recordstatus')),
                ('tags', models.ManyToManyField(blank=True, db_table='home_assets_frame_tags', related_name='frames', to='lookup.tag')),
            ],
            options={
                'db_table': 'home_assets_frame',
                'ordering': ('sort_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='FrameAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(max_length=500, upload_to=apps.utils.asset_paths.frame_asset_upload_path)),
                ('sort_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='home_assets.frame')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frame_assets', to='lookup.framekey')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frame_assets', to='lookup.recordstatus')),
            ],
            options={
                'db_table': 'home_assets_frameasset',
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='FrameConstraint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value_1', models.DecimalField(decimal_places=4, max_digits=8)),
                ('value_2', models.DecimalField(decimal_places=4, max_digits=8)),
                ('value_3', models.DecimalField(decimal_places=4, max_digits=8)),
                ('value_4', models.DecimalField(decimal_places=4, max_digits=8)),
                ('sort_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='home_assets.frame')),
            ],
            options={
                'db_table': 'home_assets_frameconstraint',
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='frame',
            index=models.Index(fields=['category', 'status', 'sort_order'], name='frame_cat_status_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='frameasset',
            index=models.Index(fields=['frame', 'status', 'sort_order'], name='frameasset_frame_status_idx'),
        ),
    ]
