# Generated by Django 5.2.17 on 2026-10-06 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_assets', '0001_initial'),
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE home_assets_frame_tags "
                        "DROP CONSTRAINT home_assets_frame_tags_pkey, "
                        "DROP CONSTRAINT home_assets_frame_tags_frame_id_tag_id_e855e804_uniq, "
                        "DROP COLUMN id, "
                        "ADD CONSTRAINT home_assets_frame_tags_pkey PRIMARY KEY (frame_id, tag_id)"
                    ),
                    reverse_sql=(
                        "ALTER TABLE home_assets_frame_tags ADD COLUMN id bigserial; "
                        "ALTER TABLE home_assets_frame_tags DROP CONSTRAINT home_assets_frame_tags_pkey; "
                        "ALTER TABLE home_assets_frame_tags ADD CONSTRAINT home_assets_frame_tags_pkey PRIMARY KEY (id); "
                        "ALTER TABLE home_assets_frame_tags ADD CONSTRAINT home_assets_frame_tags_frame_id_tag_id_e855e804_uniq UNIQUE (frame_id, tag_id)"
                    ),
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='FrameTag',
                    fields=[
                        ('pk', models.CompositePrimaryKey('frame_id', 'tag_id', blank=True, editable=False, primary_key=True, serialize=False)),
                        ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home_assets.frame')),
                        ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lookup.tag')),
                    ],
                    options={'db_table': 'home_assets_frame_tags'},
                ),
                migrations.AlterField(
                    model_name='frame',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='frames', through='home_assets.FrameTag', through_fields=('frame', 'tag'), to='lookup.tag'),
                ),
            ],
        ),
    ]
