# Generated by Django 5.2.17 on 2026-10-01 06:42

import apps.utils.asset_paths
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.SmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lookup_assetvariant',
                'ordering': ('sort_order', 'label'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EffectType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.SmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lookup_effecttype',
                'ordering': ('sort_order', 'label'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FrameKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.SmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lookup_framekey',
                'ordering': ('sort_order', 'label'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FrameType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.SmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lookup_frametype',
                'ordering': ('sort_order', 'label'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.SmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lookup_orientation',
                'ordering': ('sort_order', 'label'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecordStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.SmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lookup_recordstatus',
                'ordering': ('sort_order', 'label'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SlideType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.SmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lookup_slidetype',
                'ordering': ('sort_order', 'label'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.SmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag_type', models.CharField(choices=[('screen', 'Screen'), ('listing', 'Listing'), ('availability', 'Availability'), ('variant', 'Variant'), ('hashtag', 'Hashtag'), ('locale', 'Locale')], max_length=20)),
                ('icon', models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.utils.asset_paths.tag_icon_upload_path)),
            ],
            options={
                'db_table': 'lookup_tag',
                'ordering': ('sort_order', 'label'),
                'abstract': False,
                'indexes': [models.Index(fields=['tag_type', 'is_active', 'sort_order'], name='tag_type_active_sort_idx')],
            },
        ),
    ]
