# Generated by Django 5.2.17 on 2026-10-01 06:42

import apps.utils.asset_paths
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('cover', models.ImageField(max_length=500, upload_to=apps.utils.asset_paths.slide_cover_upload_path)),
                ('sort_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='category.category')),
                ('slide_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slides', to='lookup.slidetype')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slides', to='lookup.recordstatus')),
            ],
            options={
                'db_table': 'slides_slide',
                'ordering': ('sort_order', 'title'),
                'indexes': [models.Index(fields=['category', 'status', 'sort_order'], name='slide_cat_status_sort_idx'), models.Index(fields=['slide_type', 'status', 'sort_order'], name='slide_type_status_sort_idx')],
            },
        ),
    ]
