# Generated by Django 5.2.17 on 2026-10-01 06:42

import apps.utils.asset_paths
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(max_length=500, upload_to=apps.utils.asset_paths.font_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('ttf',))])),
                ('sort_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fonts', to='category.category')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fonts', to='lookup.recordstatus')),
                ('tags', models.ManyToManyField(blank=True, db_table='fonts_font_tags', related_name='fonts', to='lookup.tag')),
            ],
            options={
                'db_table': 'fonts_font',
                'ordering': ('sort_order', 'title'),
                'indexes': [models.Index(fields=['category', 'status', 'sort_order'], name='font_cat_status_sort_idx')],
            },
        ),
    ]
