# Generated by Django 5.2.17 on 2026-10-06 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonts', '0001_initial'),
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE fonts_font_tags "
                        "DROP CONSTRAINT fonts_font_tags_pkey, "
                        "DROP CONSTRAINT fonts_font_tags_font_id_tag_id_e54de79c_uniq, "
                        "DROP COLUMN id, "
                        "ADD CONSTRAINT fonts_font_tags_pkey PRIMARY KEY (font_id, tag_id)"
                    ),
                    reverse_sql=(
                        "ALTER TABLE fonts_font_tags ADD COLUMN id bigserial; "
                        "ALTER TABLE fonts_font_tags DROP CONSTRAINT fonts_font_tags_pkey; "
                        "ALTER TABLE fonts_font_tags ADD CONSTRAINT fonts_font_tags_pkey PRIMARY KEY (id); "
                        "ALTER TABLE fonts_font_tags ADD CONSTRAINT fonts_font_tags_font_id_tag_id_e54de79c_uniq UNIQUE (font_id, tag_id)"
                    ),
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='FontTag',
                    fields=[
                        ('pk', models.CompositePrimaryKey('font_id', 'tag_id', blank=True, editable=False, primary_key=True, serialize=False)),
                        ('font', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fonts.font')),
                        ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lookup.tag')),
                    ],
                    options={'db_table': 'fonts_font_tags'},
                ),
                migrations.AlterField(
                    model_name='font',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='fonts', through='fonts.FontTag', through_fields=('font', 'tag'), to='lookup.tag'),
                ),
            ],
        ),
    ]
