# Generated by Django 5.2.17 on 2026-10-06 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
        ('stickers', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE stickers_sticker_tags "
                        "DROP CONSTRAINT stickers_sticker_tags_pkey, "
                        "DROP CONSTRAINT stickers_sticker_tags_sticker_id_tag_id_948887c0_uniq, "
                        "DROP COLUMN id, "
                        "ADD CONSTRAINT stickers_sticker_tags_pkey PRIMARY KEY (sticker_id, tag_id)"
                    ),
                    reverse_sql=(
                        "ALTER TABLE stickers_sticker_tags ADD COLUMN id bigserial; "
                        "ALTER TABLE stickers_sticker_tags DROP CONSTRAINT stickers_sticker_tags_pkey; "
                        "ALTER TABLE stickers_sticker_tags ADD CONSTRAINT stickers_sticker_tags_pkey PRIMARY KEY (id); "
                        "ALTER TABLE stickers_sticker_tags ADD CONSTRAINT stickers_sticker_tags_sticker_id_tag_id_948887c0_uniq UNIQUE (sticker_id, tag_id)"
                    ),
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='StickerTag',
                    fields=[
                        ('pk', models.CompositePrimaryKey('sticker_id', 'tag_id', blank=True, editable=False, primary_key=True, serialize=False)),
                        ('sticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stickers.sticker')),
                        ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lookup.tag')),
                    ],
                    options={'db_table': 'stickers_sticker_tags'},
                ),
                migrations.AlterField(
                    model_name='sticker',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='stickers', through='stickers.StickerTag', through_fields=('sticker', 'tag'), to='lookup.tag'),
                ),
            ],
        ),
    ]
